services:
  web:
    container_name: web
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - "80:80"
    command: [
      "/bin/sh", "-c",
      "poetry run python src/manage.py migrate && 
      poetry run gunicorn --chdir src --bind 0.0.0.0:80 core.wsgi:application"
    ]
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: focusbrain-postgres
    image: postgres:16
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    container_name: focusbrain-redis
    image: redis:6
    restart: always
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - "6379:6379"

volumes:
  postgres:
  redis: